all: generate_circle generate_gradient

generate_circle: generate_circle.cpp
	gcc -o generate_circle generate_circle.cpp -lstdc++

generate_gradient: generate_gradient.cpp
	gcc -o generate_gradient generate_gradient.cpp -lstdc++

clean:
	rm -f generate_gradient