imageGenerator.o: src/modules/ImageGenerator.cpp
	mkdir -p build/modules
	gcc -c src/modules/ImageGenerator.cpp -o build/modules/ImageGenerator.o `Magick++-config --cppflags --cxxflags --ldflags --libs`